// tag::DE[]
|===
| Dauer: 60 Min. | Übungszeit: keine
|===

=== Begriffe und Konzepte
Innerhalb jeder akkreditierten Schulung müssen konrkete Beispiele für unterschiedliche Bereiche von Web-Architekturen vorgestellt, besprochen und bewertet werden:

  * Umgang mit Infrastruktur und insbesondere Reverse-Proxies.
  * Ein grobes Muster einer Web-Backend-Applikation.
  * Ein oder mehrere Beispiele für Single-Page-Framework Features wie Data-Binding oder Client-Side-Routing.
  * Beispiele für unterschiedliche Datenbank-Modelle.

Art und Ausprägung der vorgestellten Beispiele können von der Schulung bzw. den Interessen der Teilnehmer abhängen und werden seitens iSAQB nicht vorgegeben.

// end::DE[]


// tag::EN[]
|===
| Duration: 60 min | Practice time: none
|===

=== Terms and Principles

Specific examples of different areas of web architecture must be presented, discussed,
and evaluated within each accredited training course:

* Dealing with infrastructure and, in particular, reverse proxies.
* A rough design of a web backend application.
* One or more examples of single-page framework features such as data binding or client-side routing.
* Examples of different database models.

Type and characteristics of the presented examples can depend on the training course or the interests
of the participants and are not specified by the iSAQB.

// end::EN[]

