// tag::FEEDBACK[]
:filename: 98-examples/01-examples-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 60 Min. | Übungszeit: keine
|===

Dieser Abschnitt ist nicht prüfungsrelevant.

=== Begriffe und Konzepte
Innerhalb jeder akkreditierten Schulung müssen es konrkete Beispiele für unterschiedliche Bereiche von Web-Architekturen vorgestellt, besprochen und bewertet werden:

  * Umgang mit Infrastruktur und insbesondere Reverse-Proxies.
  * Ein grobes Muster einer Web-Backend-Applikation.
  * Ein oder mehrere Beispiele für Single-Page-Framework Features wie Data-Binding oder Client-Side-Routing.
  * Beispiele für unterschiedliche Datenbank-Modelle.

Art und Ausprägung der vorgestellten Beispiele können von der Schulung bzw. den Interessen der Teilnehmer abhängen und werden seitens iSAQB nicht vorgegeben.

// end::DE[]


// tag::EN[]
|===
| Lesson duration: XXX min | Exercises: XXX min
|===

This section is not examinable.

=== Terms and concepts
In every licensed training session, at least one example for {curriculum-short} must be presented.

Type and structure of the examples presented may depend on the training and participants' interests.
The are not prescribed by iSAQB.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen.
====
// end::REMARK[]
