// tag::DE[]
|===
| Dauer: 60 Min. | Übungszeit: keine
|===

=== Begriffe und Konzepte
Innerhalb jeder akkreditierten Schulung müssen konrkete Beispiele für unterschiedliche Bereiche von Web-Architekturen vorgestellt, besprochen und bewertet werden:

  * Umgang mit Infrastruktur und insbesondere Reverse-Proxies.
  * Ein grobes Muster einer Web-Backend-Applikation.
  * Ein oder mehrere Beispiele für Single-Page-Framework Features wie Data-Binding oder Client-Side-Routing.
  * Beispiele für unterschiedliche Datenbank-Modelle.

Art und Ausprägung der vorgestellten Beispiele können von der Schulung bzw. den Interessen der Teilnehmer abhängen und werden seitens iSAQB nicht vorgegeben.

// end::DE[]


// tag::EN[]
|===
| Duration: 60 min | Practice time: none
|===

=== Terms and Principles
Within each accredited course specific examples of different areas of web architecture must be presented, discussed and evaluated:
  
  * Dealing with infrastructure and especially reverse proxies.
  * A rough pattern of a web backend application.
  * One or more examples of single page framework features such as data binding or client side routing.
  *	Examples of different database models.

The type and character of the examples presented can depend on the course and the interests of the participants and are not prescribed by the iSAQB.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen.
====
// end::REMARK[]
