// tag::DE[]
|===
| Dauer: 180 Min. | Übungszeit: 120 Min.
|===

=== Begriffe und Konzepte
* Datenmodellierung, Funktionale Zerlegung, Repräsentationm, Verteiltes System, CAP-Theorem, ACID, Sicherheit von Web-Applikationen, Authentifizierung, Autorisierung, Barrierefreiheit/Accessibility, Internationalisierung/Lokalisierung, HTML, CSS, JavaScript, Trennen von Inhalt, Präsentation und Verhalten, Graceful Degradation, Progressive Enhancement, unobtrusive JavaScript.

// end::DE[]

// tag::EN[]
|===
| Duration: 180 min | Practice time: 120 min
|===

=== Terms and concepts
* Data modelling, Functional decomposition, Representation, Distributed system, CAP theorem, ACID, Security of web apps, Authentification, Authorization, Accessibility, Internationalization/Localization, HTML, CSS, JavaScript, Separation of content, presentation and behaviour, Graceful degradation, Progressive enhancement, Unobtrusive JavaScript.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
