// tag::FEEDBACK[]
:filename: 05-entwurf/LZ-5-01.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-5-1]]
//==== LZ 5-1: Dies ist das erste Lernziel in Kapitel 5, lorem ipsum sit dolor

**Was sollen die Teilnehmer können?**

  * Die Teilnehmer können die Belange Repräsentation, Formatierung und Interaktion klar im Markup unterscheiden und beim Entwurf von Web-Anwendungen berücksichtigen (Separation of Concerns).
  * Die Teilnehmer können verschiedene Aufgaben der Client-Oberfläche Formaten aus dem Kanon der Web-Standards zuordnen:
    ** HTML liefert die Strukturdaten
    ** CSS legt die Präsentation fest. Selektoren wählen dabei Elemente aus der HTML-Struktur und weisen ihnen Präsentationseigenschaften zu.
    ** JavaScript steuert das Verhalten, verleiht über Event-Handler Interaktivität und ermöglicht asynchrone Serverkommunikation (AJAX).

**Was sollen die Teilnehmer verstehen?**

  * Die Teilnehmer verstehen die Notwendigkeit von Regeln, die beim Einsatz von Request-Response-Frameworks sicherstellen, dass nur erwünschte Funktionalitäten in den Views/Templates implementiert werden. 
  * Die Teilnehmer verstehen, dass sich die Reaktionsfähigkeit des Systems durch geeigneten Einsatz von asynchroner Verarbeitung oft verbessern lässt.
  * Die Teilnehmer verstehen die grundsätzliche Aussage des CAP-Theorems und wissen, dass zwischen Skalierbarkeit/Verfügbarkeit/Verteiltheit und Konsistenz/Aktualität der Daten ein Kompromiss gesucht werden muss.
  * Die Teilnehmer verstehen, wie Netzwerk-Fehler in verteilten Systemen Inkonsistenzen oder besondere Fehlerzustände hervorrufen können.
  * Die Teilnehmer verstehen, wie sich Architekturen für konsistente Systeme und Systeme mit Partitionstoleranz unterscheiden.
  * Die Teilnehmer verstehen, wie Angreifer Sicherheitslücken mit Hilfe von SQL-Injection, per Cross-Site-Scripting (XSS) oder per Client-Side-Request-Forgery (CSRF) ausnutzen können.
  * Die Teilnehmer verstehen das Transaktionskonzept ACID – Atomicity, Consistency, Isolation und Durability.
  * Die Teilnehmer verstehen das Konzept der Eventual Consistency (konsistent nach einiger Verzögerung).
  * Die Teilnehmer verstehen, dass die innere Architektur der Server-Seite zusätzlich zu den fachlichen Aspekten auch durch
    ** die Philosophie des verwendeten Frameworks, 
    ** Strategien zum Caching von statischen und dynamischen Inhalten sowie 
    ** Strategien zur Skalierung der Applikation getrieben wird.
  * Die Teilnehmer verstehen, dass sich für lang laufende Prozesse Integrationsmuster wie Messaging für eine lose Kopplung der Web-Applikation an eine Hintergrundverarbeitung anbieten. 
  * Die Teilnehmer verstehen, dass jede Anwendung, die aus öffentlichen Netzen erreichbar ist, angegriffen wird.

**Was sollen die Teilnehmer kennen?**

  * Die Teilnehmer  kennen die Muster Command-Query-Separation, CQS, und Command-Query-Responsibility-Separation, CQRS, um sowohl funktionale als auch die nicht-funktionale Anforderungen gezielt zu erfüllen.
  * Die Teilnehmer wissen, dass es sich bei der Consistency aus „ACID“ um eine andere Konsistenz handelt als bei der Consistency aus CAP.
  * Die Teilnehmer kennen die Grundmechanismen, mit denen im eigenen Technologieportfolio SQL-Injection, Cross-Site-Scripting (XSS) und Client-Side-Request-Forgery (CSRF) verhindert werden.
  * Die Teilnehmer kennen für gestellte Qualitätsanforderungen verschiedene Strategien zur Verwaltung von sitzungsbezogenen Daten, z. B. im Cookie, im Hauptspeicher des Servers, in einer Datenbank.
  * Die Teilnehmer kennen den Unterschied zwischen Internationalisierung und Lokalisierung.
  * Die Teilnehmer kennen verschiedene Strategien mit denen ein Client über das Ergebnis einer Aktivität informiert werden kann, die asynchron auf dem Server gestartet wurde. Z.B.:
    ** Polling (Client Pull)
    ** HTML5 Server Sent Events
    ** Websockets.
  * Die Teilnehmer wissen, dass viele serverseitige Frameworks Plug-Ins, analog zum Pipes-And-Filter Muster erlauben, beispielsweise ServletFilter in Java Servlet API basierten Frameworks oder HttpModules in ASP.NET.  
  * Die Teilnehmer kennen zumindest ein serverseitiges Framework, mit dem sich Web-Anwendungen realisieren lassen.
  * Die Teilnehmer kennen unterschiedliche Arten von serverseitigen Web-Frameworks:
    ** Komponenten-Frameworks versuchen ein Event-basiertes Programmier-Modell aus dem Bereich der Desktop-Applikationen zu übertragen.
    ** Action- oder Request-Response-Frameworks bilden das HTTP-Protokoll unmittelbar ab.  
    ** Daten-getriebene Frameworks bilden zur Datenerfassung Datenbank-Tabellen in der Oberfläche ab.
  * Die Teilnehmer kennen Authentifizierungsmechanismen wie OpenID Connect oder CAS.

// end::DE[]

// tag::EN[]
[[LG-5-1]]
//==== LG 5-1: TBD

**What should participants be able to do?**

  *	Participants can clearly differentiate the importance of representation, formatting and interaction in markup and take them into account in the design of web apps (separation of concerns).
  *	Participants can classify different tasks of the client interface formats from the existing web standards:
    ** HTML provides the structure data
    ** CSS defines the presentation. Selectors select elements from the HTML structure and assign them presentation characteristics.
    ** JavaScript controls the behaviour, grants interactivity via event handlers and enables asynchronous server communication (AJAX).

**What should participants understand?**

  *	Participants understand the need for rules that ensure when using request-response frameworks that only desired functionality is implemented in the views/templates.
  *	Participants understand that the responsiveness of the system can often be improved by appropriate use of asynchronous processing.
  *	Participants understand the basic significance of the CAP theorem and know that a compromise must be found between scalability/availability/distribution and consistency/currentness.
  *	Participants understand how network errors in distributed systems can cause inconsistencies or special error states.
  *	Participants understand how architectures for consistent systems and systems with partition tolerance differ.
  *	Participants understand how attackers can exploit vulnerabilities using SQL injection, cross-site scripting (XSS) or client side request forgery (CSRF).
  *	Participants understand the transaction concept ACID – Atomicity, Consistency, Isolation and Durability.
  *	Participants understand the concept of Eventual Consistency (consistent after some delay).
  *	Participants understand that the inner architecture of the server side, in addition to the technical aspects, is also affected by
    ** the philosophy of the framework used, 
    ** strategies for caching of static and dynamic content and 
    ** strategies for scaling the application.
  *	Participants understand that integration patterns such as messaging for a loose coupling of the web apps to background processing are suitable for long-running processes. 
  *	Participants understand that any application accessible from public networks will be attacked.

**What should participants know?**

  *	Participants know the patterns of Command Query Separation, CQS, and Command Query Responsibility Separation, CQRS, in order to specifically meet both functional and non-functional requirements.
  *	Participants know that the consistency from "ACID" is a different consistency than the consistency from CAP.
  *	Participants know the basic mechanisms used to prevent SQL injection, cross site scripting (XSS) and client side request forgery (CSRF) in their own technology portfolio.
  *	Participants know various strategies for management of session-related data, e.g. in the cookie, in the main memory of the server, in a database, to comply with quality requirements.
  *	Participants know the difference between internationalization and localization.
  *	Participants know different strategies with which a client can be informed of the result of an activity that was started asynchronously on the server. For example:
   **	Polling (client pull)
   **	HTML5 server sent events
   **	Web sockets. 
  *	Participants know that many server side frameworks allow plug-ins, analogous to the pipes and filter pattern, for example servlet filters in Java Servlet API based frameworks or HttpModules in ASP.NET.  
  *	Participants know at least one server side framework that can be used to implement web apps.
  *	Participants know different types of server side web frameworks:
   **	Component frameworks attempt to transfer an event-based programming model from the area of desktop applications.
   **	Action or request response frameworks represent the HTTP protocol directly.  
   **	Data-driven frameworks represent database tables in the interface for data input.
  * Participants know authentication mechanisms such as OpenId Connect or CAS.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
