// tag::FEEDBACK[]
:filename: 02-protokolle/01-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
|===
| Dauer: 90 Min. | Übungszeit: keine
|===

=== Begriffe und Konzepte
* URI, URL, URN, HTTP/1.1, HTTP/2, HTTP/3, HTTP-Verben (GET, PUT, POST, DELETE), HTTP-Header, Intermediaries, Caching, Content-Types, Content-Negotiation, TLS, PKI, HTML, DOM, Web-Sockets, Server-Sent Events, CustomElements, Shadow DOM, OAuth 2, OpenID Connect., CORS, Content Security Policy

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 90 min | Exercises: none
|===

=== Terms and concepts
* URI, URL, URN, HTTP/1.1, HTTP/2, HTTP/3, HTTP verbs (GET, PUT, POST, DELETE), HTTP headers, Intermediaries, Caching, Content types, Content negotiation, TLS, PKI, HTML, DOM, Web sockets, Server-sent events, CustomElements, Shadow DOM, OAuth 2, OpenID Connect., CORS, Content Security Policy.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
