=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
//==== LZ 5-1: Dies ist das erste Lernziel in Kapitel 5, lorem ipsum sit dolor

**Was sollen die Teilnehmer verstehen?**

* Die Teilnehmer verstehen die Grundlagen der Risikoanalyse und Bedrohungsmodellierung.
* Die Teilnehmer verstehen die Prinzipien für ein sicheres Software-Design:
** Principle of Least Privilege: gib Benutzern und Komponenten nur so viele Rechte, wie sie unbedingt benötigen.
** Defense in Depth: vertraue nicht darauf, dass andere Sicherheitsmaßnahmen funktioniert haben – verwende redundante Prüfungen.
** Secure by Default: Rechte müssen explizit erteilt werden.
** Don’t trust anybody: Benutzereingaben und Daten externer Quellen müssen validiert werden.
** Compartmentalize: Trenne Komponenten, die verschiedene Rechte benötigen voneinander.
** Fail securely: Falls Fehler auftreten, dürfen keine sicherheitsrelevanten Informationen preisgegeben werden.
* Die Teilnehmer verstehen, dass die Anzahl der Zugriffe im Internet sprunghaft über alle erwarteten Maße hinaus steigen kann.
* Die Teilnehmer verstehen, dass Backend-Systeme (wie z.B. Datenbanken oder Enterprise Informationssysteme) leicht unter Last geraten, wenn die Anzahl der Requests steigt, weil häufig ein Request zu einer Menge von Anfragen ans Backend führt.
* Die Teilnehmer verstehen, dass sich mit verschiedenen Persistenzstrategien (z.B. Relational, Aggregat/Dokumenten-orientiert, Spalten-orientiert, Hierarchisch, Objektorientiert, Graphenorientiert) verschiedene Nutzungsszenarien unterschiedlich gut unterstützen lassen.
* Die Teilnehmer verstehen, dass die Qualität sowohl von der Angemessenheit der ausgewählten Technologie als auch von der konkreten Implementierung abhängen.
* Die Teilnehmer verstehen, dass Internationalisierung mehr bedeutet, als Inhalte in verschiedenen Sprachen anzubieten.  Etwa
** Formate für Zahlen oder Datumsangaben oder die Reihenfolge, in der Worte sortiert werden, hängen vom Kulturkreis ab.
** Schriftrichtungen können sich unterscheiden.
** Layouts müssen berücksichtigen, dass Texte in verschiedenen Sprachen unterschiedlich viel Platz beanspruchen.
** Die rechtlichen Rahmenbedingungen in unterschiedlichen Staaten müssen berücksichtigt werden.
** Kulturelle Unterschiede wirken sich beispielsweise auf die Wahl von Farben aus.

**Was sollen die Teilnehmer kennen?**

* Die Teilnehmer kennen die wesentlichen Kennzahlen, die für den Betrieb einer Web-Anwendung relevant sind:
** Anzahl von Prozessen / Threads
** RAM-Verbrauch
** Durchschnittlicher Ressourcenverbauch pro Request
** Anzahl offener Connections
** Durchschnittliche Antwortzeit

// end::DE[]

// tag::EN[]
[[LG-6-1]]
//==== LG 5-1: TBD

**What should participants understand?**

* The participants understand the basics of risk analysis and threat modeling.
* The participants understand the principles of secure software design:
** Principle of Least Privilege: give users and components only as many rights as they absolutely need.
** Defense in Depth: do not trust that other security measures have worked – use redundant checks.
** Secure by Default: rights must be granted explicitly.
** Don’t trust anybody: user input and data from external sources must be validated.
** Compartmentalize: separate components that require different rights from each other.
** Fail securely: if errors occur, no security-relevant information may be disclosed.
* The participants understand that the number of accesses to the Internet can increase in leaps and bounds beyond all expected levels.
* The participants understand that backend systems (such as databases or enterprise information systems) can easily become overloaded when the number of requests increases because one request often leads to a lot of queries to the backend.
* The participants understand that different persistence strategies (for example, relational, aggregate/document-oriented, column-oriented, hierarchical, object-oriented, graph-oriented) can support different usage scenarios with varying degrees of success.
* The participants understand that quality depends on both the appropriateness of the chosen technology and the specific implementation.
* The participants understand that internationalization means more than just offering content in different languages. For example:
** Formats for numbers or dates or the order in which words are sorted depend on the culture.
** Text directions may differ.
** Layouts must take into account that texts in different languages take up different amounts of space.
** The legal framework in different countries must be taken into account.
** Cultural differences affect, for example, the choice of colors.


**What should participants know?**

* The participants know the key figures that are relevant to the operation of a web application:
** Number of processes/threads
** RAM usage
** Average resource consumption per request
** Number of open connections
** Average response time

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
