=== {learning-goals}

// tag::DE[]
[[LZ-6-1]]
//==== LZ 5-1: Dies ist das erste Lernziel in Kapitel 5, lorem ipsum sit dolor

**Was sollen die Teilnehmer verstehen?**

  * Die Teilnehmer verstehen die Grundlagen der Risikoanalyse und Bedrohungsmodellierung.
  *	Die Teilnehmer verstehen die Prinzipien für ein sicheres Software-Design:
    ** Principle of Least Privilege: gib Benutzern und Komponenten nur so viele Rechte, wie sie unbedingt benötigen.
    ** Defense in Depth: vertraue nicht darauf, dass andere Sicherheitsmaßnahmen funktioniert haben – verwende redundante Prüfungen.
    ** Secure by Default: Rechte müssen explizit erteilt werden.
    ** Don’t trust anybody: Benutzereingaben und Daten externer Quellen müssen validiert werden.
    ** Compartmentalize: Trenne Komponenten, die verschiedene Rechte benötigen voneinander.
    ** Fail securely: Falls Fehler auftreten, dürfen keine sicherheitsrelevanten Informationen preisgegeben werden.
  *	Die Teilnehmer verstehen, dass die Anzahl der Zugriffe im Internet sprunghaft über alle erwarteten Maße hinaus steigen kann.
  *	Die Teilnehmer verstehen, dass Backend-Systeme (wie z.B. Datenbanken oder Enterprise Informationssysteme) leicht unter Last geraten, wenn die Anzahl der Requests steigt, weil häufig ein Request zu einer Menge von Anfragen ans Backend führt.
  *	Die Teilnehmer verstehen, dass sich mit verschiedenen Persistenzstrategien (z.B. Relational, Aggregat/Dokumenten-orientiert, Spalten-orientiert, Hierarchisch, Objektorientiert, Graphenorientiert) verschiedene Nutzungsszenarien unterschiedlich gut unterstützen lassen.
  *	Die Teilnehmer verstehen, dass die Qualität sowohl von der Angemessenheit der ausgewählten Technologie als auch von der konkreten Implementierung abhängen.
  *	Die Teilnehmer verstehen, dass Internationalisierung mehr bedeutet, als Inhalte in verschiedenen Sprachen anzubieten.  Etwa
    ** Formate für Zahlen oder Datumsangaben oder die Reihenfolge, in der Worte sortiert werden, hängen vom Kulturkreis ab.
    ** Schriftrichtungen können sich unterscheiden.
    ** Layouts müssen berücksichtigen, dass Texte in verschiedenen Sprachen unterschiedlich viel Platz beanspruchen.
    ** Die rechtlichen Rahmenbedingungen in unterschiedlichen Staaten müssen berücksichtigt werden.
    ** Kulturelle Unterschiede wirken sich beispielsweise auf die Wahl von Farben aus.

**Was sollen die Teilnehmer kennen?**

  * Die Teilnehmer kennen die wesentlichen Kennzahlen, die für den Betrieb einer Web-Anwendung relevant sind:
    ** Anzahl von Prozessen / Threads
    ** RAM-Verbrauch
    ** Durchschnittlicher Ressourcenverbauch pro Request
    ** Anzahl offener Connections
    ** Durchschnittliche Antwortzeit

// end::DE[]

// tag::EN[]
[[LG-6-1]]
//==== LG 5-1: TBD

**What should participants be able to do?**

  *	Participants can explain and apply the fundamentals of risk analysis and threat modelling.
  *	Participants can apply the principles for a secure software design:
    ** Principle of least privilege: give users and components only as many rights as they absolutely need.
    ** Defence in depth: do not rely on other security measures – use redundant checks.
    ** Secure by default: Rights must be granted explicitly.
    ** Don’t trust anybody: User input and data from external sources must be validated.
    ** Compartmentalize: Separate components that need different rights.
    ** Fail securely: If errors occur, no security-related information must be exposed.
  *	Participants can explain and demonstrate with examples that internationalization means more than offering content in different languages.  For example:
    ** Formats for numbers or dates or the sequence in which words are sorted depends on the cultural environment.
    ** Text directions can differ.
    ** Layouts must take into account that texts in different languages need different amounts of space.
    ** The legal requirements in different countries must be taken into account.
    ** Cultural differences affect the choice of colours, for example.

**What should participants understand?**

  *	Participants understand the basics of risk analysis and threat modelling.
  *	Participants understand the principles of secure software design:
    ** Principle of Least Privilege: give users and components only as many rights as they absolutely need.
    ** Defense in Depth: do not trust that other security measures have worked - use redundant checks.
    ** Secure by Default: rights must be granted explicitly.
    ** Don't trust anybody: user input and data from external sources must be validated.
    ** Compartmentalize: Separate components that require different rights from each other.
    ** Fail securely: If errors occur, no security-relevant information may be disclosed.
  *	Participants understand that the number of accesses to the Internet can increase by leaps and bounds beyond all expected levels.
  *	Participants understand that backend systems (such as databases or enterprise information systems) can easily become overloaded if the number of requests increases because a request frequently leads to numerous queries to the backend.
  *	Participants understand that different persistence strategies (e. g., relational, aggregation/document-oriented, column-oriented, hierarchical, object-oriented, graph-oriented) can be used to support different utilization scenarios with varying degrees of effectiveness.
  *	Participants understand that the quality depends both on the suitability of the chosen technology and on the specific implementation.
  *	Participants understand that internationalization means more than just providing content in different languages. For instance:
    ** Formats for numbers or dates or the order in which words are sorted depend on the cultural area.
    ** Font directions may differ.
    ** Layouts must take into account that texts in different languages take up different amounts of space.
    ** The legal framework in different countries must be taken into account.
    ** Cultural differences affect, for example, the choice of colors.

**What should participants know?**

  *	Participants know the essential performance indicators that are relevant for operation of a web application:
    ** Number of processes/threads
    ** RAM utilization
    ** Average resource consumption per request
    ** Number of open connections
    ** Average response time
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
