=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
//==== LZ 1-1: Dies ist das erste Lernziel, in Kategorie xy
In diesem Abschnitt sollen technologieunabhängig Konzepte aus dem Web-Umfeld behandelt werden.

**Was sollen die Teilnehmer können?**

  * Die Teilnehmer können den typischen Request-/Response-Verlauf erläutern, der bei der Eingabe einer Adresse in der Adresszeile des Browsers bzw. beim Absenden eines Formulars abläuft.
  * Teilnehmer können den Request-/Response-Verlauf auf typische Komponenten im Web-Umfeld abbilden: Client, Server, Proxy, Reverse Proxy, Load-Balancer, DNS-Server, Framework, eigene Applikationslogik (Servlet, PHP-Script, Rails-Controller).
  * Die Teilnehmer können den Unterschied zwischen GET und POST-Request erläutern.
  * Die Teilnehmer können schematisch die typische Client-Server-Infrastruktur von Web-Architekturen skizzieren.
  * Teilnehmer können den allgemeinen Aufbau von HTTP-Requests erläutern: Header (mit Hostname, Content-Type usw.), Content.
  * Teilnehmer können den allgemeinen Aufbau von HTTP-Responses erläutern: Response mit Statuszeile, Header und Content.
  * Die Teilnehmer können den Aufbau einer URI erläutern und die Komponenten in der Request-Verarbeitung, die tendenziell dafür zuständig sind, sie zu interpretieren. 

**Was sollen die Teilnehmer verstehen?**

  * Die Teilnehmer verstehen, dass sich hinter dem Oberbegriff Web-Applikation sowohl technisch als auch fachlich grundlegend verschiedene Arten von IT-Systemen verbergen können, die verschiedene Architekturen erfordern
  * Die Teilnehmer verstehen, dass Web-Applikationen nicht auf die Verwendung durch Browser beschränkt sind, sondern können auch durch andere Clients genutzt werden
  * Die Teilnehmer verstehen den Unterschied zwischen inhaltlicher bzw. struktureller und darstellungsspezifischer Auszeichnung von Inhalten im Sinne der Separation of Concerns.
  * Die  Teilnehmer verstehen die allgemeinen Anforderungen der Web Content Accessibility Guidelines (WCAG), die unter dem Begriff Barrierefreiheit zusammengefasst sind.
  * Die  Teilnehmer verstehen den meist für Web-Anwendungen angewandten Flow bei Single Sign On Mechanismen (Redirect, Login, Redirect mit Token, Validierung des Tokens).
  * Die Teilnehmer verstehen, dass eine Ressource mehr als eine Datenbank-Entität ist (also z.B. auch eine Prozess-Instanz oder ein Prozessschritt).
  * Die Teilnehmer verstehen, dass Hypermedia dazu dient Ressourcen miteinander in Verbindung zu setzten.
  * Die Teilnehmer verstehen das Konzept von Präprozessoren zur Übersetzung einer Sprache in eine andere bzw. zur Einbettung von Abhängigkeiten oder zur Erkennung toter Code-Blöcke.

**Was sollen die Teilnehmer kennen?**

  * Die Teilnehmer wissen, dass rechtliche Rahmenbedingungen barrierefreie Oberflächen verlangen können. Z. B. formuliert die „Verordnung zur Schaffung barrierefreier Informationstechnik nach dem Behindertengleichstellungsgesetz“ etwa konkrete Anforderungen, die von allen Web-Seiten der Bundesverwaltung der Bundesrepublik Deutschland umgesetzt werden müssen.
  * Die Teilnehmer kennen einige  der Techniken, die zu barrierefreien Inhalten führen, sorgen gleichzeitig dafür, dass diese Inhalte auch leichter maschinell verarbeitet werden können.
  * Die Teilnehmer kennen verschiedene Charakteristika von Web-Frameworks:
    ** Komponenten- sowie Request-Response-Frameworks nutzen häufig vom MVC-Muster beeinflusste Designs
    ** Request-Response-Frameworks sind strukturell meist relativ gleich aufgebaut: Actions nehmen den Request entgegen, führen Applikationslogik aus und rendern zum Schluss die Response meist mit Templating (HTML) oder Objekt-Serialisierung (JSON/XML)
  * Die Teilnehmer kennen mit dem Konzept von Pattern-Libraries eine Möglichkeit Frontend-Komponenten zu dokumentieren.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
//==== LG 1-1: The is the first learning goal, in category xy
In this chapter, technology-independent concepts from the Web environment are discussed.

**What should participants be able to do?**

  *	Participants can explain the typical request/response process that takes place when an address is entered in the address line of the browser or when a form is sent.
  *	Participants can map the request/response process onto typical components in the web environment: client, server, proxy, reverse proxy, load balancer, DNS server, framework, own application logic (servlet, PHP script, Rails controller).
  *	Participants can explain the difference between a GET and POST request.
  *	Participants can make a diagram of the typical client-server infrastructure of web architectures.
  *	Participants can explain the general structure of HTTP requests: header (with host name, content type, etc.), content.
  *	Participants can explain the general structure of HTTP responses: response with status line, header and content.
  *	Participants can explain the structure of a URI and interpret the components in the request process that tend to be responsible for it. 
  *	The participants can outline how a website with Ajax differs from the classic round-trip scheme without Ajax.
  *	The participants can explain the advantages of a stateless server regarding its scalability.
  *	The participants can split Web UIs into frontend components.

**What should participants understand?**

  *	Participants understand that the generic term web app can comprise fundamentally different types of IT systems with respect both to technology and content and that these systems require different architectures.
  *	Participants understand that web apps are not restricted to use by browsers, but can also be used by other clients.
  *	Participants understand the difference between structural and presentational characterization of content according to the Separation of Concerns.
  *	Participants understand the general requirements of the Web Content Accessibility Guidelines (WCAG), which are summarized under the term accessibility.
  *	Participants understand the flow of Single-Sign-On mechanisms (redirect, login, redirect with token, validation of the token), which is mostly used for web applications.
  *	Participants understand that a resource is more than just a database entity (e. g., also a process instance or a process step).
  *	Participants understand that hypermedia is used to connect resources to each other.
  *	Participants understand the concept of preprocessors for translating one language into another or for embedding dependencies or detecting dead code blocks.

**What should participants know?**

  *	Participants know that legal conditions can require barrier-free user interfaces. For example, the “Regulation on the creation of barrier-free information technology in accordance with the law on equal opportunities for the disabled” defines specific requirements that must be implemented by all websites of the Federal Administration of the Federal Republic of Germany.
  *	Some of the techniques that lead to barrier-free content also ensure that this content can be processed more easily by machine.
  *	Participants know different characteristics of web frameworks:
   **	Component and request-response frameworks often use designs influenced by the MVC pattern.
   **	Request-response frameworks are structurally mostly build in a relatively similar way: Actions accept the request, execute application logic and finally render the response, usually with templating (HTML) or object serialization (JSON/XML).
  *	Participants will be familiar with the concept of pattern libraries as a way of documenting front-end components.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
